// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGugp7KcMYLlfPhjcD4qDO9zHSqtxA08Q',
    appId: '1:608082226703:web:35a52ac7600d05d080bd7a',
    messagingSenderId: '608082226703',
    projectId: 'drhouse-a8e6b',
    authDomain: 'drhouse-a8e6b.firebaseapp.com',
    storageBucket: 'drhouse-a8e6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCEbgenoSvYKarrF_YzfP-hL1UCyt0msA',
    appId: '1:91056879642:android:a39d5631ad42592c3ab9a3',
    messagingSenderId: '91056879642',
    projectId: 'customer-99256',
    storageBucket: 'customer-99256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJxgSofw8RpiaWBZJDT_2a8IeOmOmLzU8',
    appId: '1:608082226703:ios:ab8dca707d7613c680bd7a',
    messagingSenderId: '608082226703',
    projectId: 'drhouse-a8e6b',
    storageBucket: 'drhouse-a8e6b.appspot.com',
    iosBundleId: 'com.example.drhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJxgSofw8RpiaWBZJDT_2a8IeOmOmLzU8',
    appId: '1:608082226703:ios:ab8dca707d7613c680bd7a',
    messagingSenderId: '608082226703',
    projectId: 'drhouse-a8e6b',
    storageBucket: 'drhouse-a8e6b.appspot.com',
    iosBundleId: 'com.example.drhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGugp7KcMYLlfPhjcD4qDO9zHSqtxA08Q',
    appId: '1:608082226703:web:cf1428656c100e0480bd7a',
    messagingSenderId: '608082226703',
    projectId: 'drhouse-a8e6b',
    authDomain: 'drhouse-a8e6b.firebaseapp.com',
    storageBucket: 'drhouse-a8e6b.appspot.com',
  );

}